spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
        ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
logging:
  level:
    org.springframework.security: DEBUG          # General Spring Security logging
    org.springframework.security.web.access: DEBUG  # Logs access control decisions
    org.springframework.security.authentication: DEBUG  # Authentication logging
    org.springframework.security.web.authentication: DEBUG  # Shows authentication filter logs
    org.springframework.security.config: DEBUG  # Shows Spring Security configuration details
    org.springframework.security.web.filter: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
